### ISSUE TITLE
Wrong Collision

### ISSUE THREAD

**Issue by gyrozco** [buff0000n/dojocad#10]
Hi! First of all I'm a big fan. I love how you've made and continue to make so many mandachord songs. I've also just found out about dojocad and it's really great! But I wanted to let you know about an error I found, probably just a mistaken boundary. While recreating my dojo's layout I ran into a collision error between a reactor and infested room on different floors, which is incorrect since they've already been made. Here are some screenshots

![Screenshot 2020-12-24 002921](https://user-images.githubusercontent.com/76552363/103075253-124b7e80-4580-11eb-8ab6-fb66e00e7455.png)
![Screenshot 2020-12-24 002852](https://user-images.githubusercontent.com/76552363/103075255-12e41500-4580-11eb-8221-f076bde1ea57.png)

Everything else so far seems fine. Thank you and keep up the good work!

**Comment by buff0000n** [comment]
@gyrozco Thanks for the heads up!  Looks like I forgot to set the ceiling bounds Entradi Audience Chamber and Infested Chamber in the right place.  It should be fixed now.
