### ISSUE TITLE
Orokin lab collision

### ISSUE THREAD

**Issue by zaza7** [buff0000n/dojocad#11]
According to this layout, the orokin lab should fit next to the dueling room, however trying to place it next to it results in a not enough space error in game, i think the collision is with the duel room which is currently being removed in an attempt to place the orokin lab where they layout has it.

https://buff0000n.github.io/dojocad/?v=2,-181,130,3&mz=BYJgNAtAzOCMYAZEH0DGrI0gFgOyJXU3AlwE4CE0NoTZ7LrjJZspGAnAUwIlfaSxk3XvXiDhPJKQoSR0vASEiIANmws2BKJMjqWDJDpX6Z23Wo0RFR5MHa0w8cWh7Ww2Cs7tWs8cFSobqpInuaoAC7MYfA6kdEU4HHBoYlgOgAmGcywZOzsIGgARgkEhcAArDnpKAA2UV747EK1brgAHE5N6ci1NO3SsFX5vSWsLMNOTI58DALIAPYcLB4Uzb0LToNa6xHAzGr5hMuWBrE9RI5h8wsYsFDSqkdCqAAeTqp6z4sAhiwdXxqcXeEAGgPWCxKMxAUDWhBoWD4OxQGQArqI5k4gA

![screenshot](https://user-images.githubusercontent.com/4474031/105644761-4529b080-5e65-11eb-87ea-cebe3c65d042.png)

**Comment by buff0000n** [comment]
@zaza7 It's the obstacle course.  Looks like the orikin lab is about 2m longer than I thought it was.

**Comment by buff0000n** [comment]
I've fixed the Orokin Lab bounds, your layout now correctly shows up with errors.  Sorry about that, I hope that doesn't cost you too much time.  You should be able to swap sides with the Orokin Lab/Dueling Room and Crimson Branch and have it still fit.

**Comment by zaza7** [comment]
Thanks for the quick fix, time's not a problem as I had plans to move the obstacle course and course architect to another floor higher up
