### ISSUE TITLE
Cannot save, and kept restarting

### ISSUE THREAD

**Issue by Jupiter60Saturn5** [buff0000n/dojocad#12]
When I tried to save my dojo, it would give me a url code.
Then when it crashed and wiped my dojo - how do I get what I have created back?

Looks like an awesome program, it's just a little unstable.

**Comment by buff0000n** [comment]
The URL *is* your saved Dojo.  Your layout is embedded in that URL.

What do you mean by crashed?  Your browser crashed, or something went wrong with the app itself?  What browser are you using?

**Comment by Jupiter60Saturn5** [comment]
I use Chrome on a windows 10 pc. Twice I was arranging rooms on the 3rd
floor, when the program just started over on level one, and everything was
gone.

**Comment by buff0000n** [comment]
Could you have accidentally hit the backspace key or otherwise navigated to a previous URL?  If that happens then you should be able to navigate forward again in your browser history and have the layout restored.

**Comment by Jupiter60Saturn5** [comment]
I'll check it out when I get home. I may have accidentally hit a key while
placing things. I did save out the urls to a text file, so I'll check that
out first. Thank you so much.

Jupiter60

**Comment by buff0000n** [comment]
If you see it crash again then can you open up the console in Chrome (ctrl-alt-I) and see if there are any errors listed in there?

**Comment by Jupiter60Saturn5** [comment]
Absolutely! I will immediately send you what I can. Thank you so much for
your help.

**Comment by Jupiter60Saturn5** [comment]
As you explained,  by putting in the URL, I have my design back.

Thank you.  I'll make sure I'm very aware of what I am pressing and
clicking on, and if a reset happens again I'll let you know.
Thanks again!
