### ISSUE TITLE
Building space error.

### ISSUE THREAD

**Issue by CobaltRat** [buff0000n/dojocad#18]
While building my layout there was an error with spacing, on web sais there is not enough space to place barracks while in game sais there is.
![2](https://user-images.githubusercontent.com/85037088/120085328-e52b6b00-c0df-11eb-9a7b-d4f70161ec9e.png)

![1](https://user-images.githubusercontent.com/85037088/120083357-ca9dc580-c0d0-11eb-9aa0-51bc397d571e.png)

**Comment by buff0000n** [comment]
Thanks for the heads up.  I could have sworn I test this a long time ago, but they did adjust the observatory bounds about a year ago.  It should be fixed now.

**Comment by CobaltRat** [comment]
it is, thanks :)
