### ISSUE TITLE
Dojo bounds on Clan Hall may have changed in a way that isn't accounted for?

### ISSUE THREAD

**Issue by adrienne** [buff0000n/dojocad#20]
I say that because this works in my actual Dojo now (I literally just added the Clan Hall yesterday and it's sitting there in my dojo) but throws an error in DojoCAD: 
![image](https://user-images.githubusercontent.com/89705/128613572-d86c5e85-3804-408c-9e98-923d66b43a0d.png)

**Comment by buff0000n** [comment]
Can you send me an in-game screenshot showing your map?  The Clan Hall is one of the room I can't really test myself.

**Comment by adrienne** [comment]
@buff0000n here's the relevant segment: 
![image](https://user-images.githubusercontent.com/89705/128648214-1e007141-3195-4930-b620-66a58522d66b.png)

**Comment by buff0000n** [comment]
@adrienne Thanks!  Yeah, they took a notch out of the starter hall bounds a year or two ago and I'm still narrowing it down.

I'll have this fixed some time this week when I'm back home.

**Comment by buff0000n** [comment]
@adrienne It's fixed now.  Thanks!

If it's not too much trouble, if you're able to temporarily remove that elevator and try placing a Tenno Lab in that spot then that would help me narrow down that notch even more.  It's okay if you can't, someone will try it eventually.

**Comment by adrienne** [comment]
@buff0000n i cannot, i'm afraid; that chunk of the dojo is not easily modifiable (too many child rooms). Thanks!
