### ISSUE TITLE
Bug: New forest room doesn't have correct dimensions

### ISSUE THREAD

**Issue by adrienne** [buff0000n/dojocad#29]
Try to build one with a reactor room underneath it and it says "insufficient space". Might need to measure some more!

**Comment by buff0000n** [comment]
@adrienne Can you give the exact layout you're trying?  I can build a reactor under the tree room.

**Comment by adrienne** [comment]
Yeah, my fault, @buff0000n - something else is in the way and wasn't showing up properly, totally my bad.
