### ISSUE TITLE
The collision in your Dojo CAD app

### ISSUE THREAD

**Issue by Zarzab** [buff0000n/dojocad#3]
I duplicates my Dojo layout how it is in game and these are the errors I received. I will be linking my CAD Layout of my dojo for you to review. I hope this helps you. 
DOJO Link: https://buff0000n.github.io/dojocad/index.html?v=2,-52,164,2&mz=BYRgNADJ0Q+gxgU2gFhWAtOATLY3oMA2dKOYAZkJGwA4YF5oQjNw54moMV6tJG1VvzgAnZBQIs2YELHGZJs4eAryJBHn3ByFSrCtnrFm3jLUKM+6fzWdCtbu0FOaMuAHtRi8BkfmEAA8wfX9+OXhgkkwwnSDlblijSLAATmEkiOCaPkz4kFTNPJTsbHQ-JyMAEyqQolzKuAAbABdMaKxaAFZZASbkDFTykDRetSamYnL03twmgCMTTFT6HFgmjyWMbAgpAWBysyxRuKRqAHYCMgQ2pxOQhGQ6NnuIrhf0K9gPRe4zAlwZ222lGBDswSc51YXxS3B29C+LWAhGwXWhAg8TBAFDhaLAUm+AEM2CNMKj0WoqgBXQg4z4CFLWUZULLUZlGYA9WLsiLeHIfEKyIA

**Comment by buff0000n** [comment]
Working on it.  Fixing your specific issue caused other discrepancies, so I need to do another pass over all the room combinations now that I have a way to get "real" measurements on the ones you can get out into the skybox with (Observatory, Orokin Lab, Elevator kind of)

**Comment by buff0000n** [comment]
Okay, went through and did some re-testing and re-measuring.  Your layout is all green now.  Thanks!
