### ISSUE TITLE
Clan hall hitbox

### ISSUE THREAD

**Issue by manuelando** [buff0000n/dojocad#32]
Here's my screen comparation. https://imgur.com/a/66o5jKl

The dojo room "Clan Hall" has the wrong hitbox dimensions, in the screen you can see "as the dojo planner shows" at right the impossibility to build cause of space issues, on the LEFT you figure out the planner is totally wrong (xD) because im actually building that room.

**Comment by buff0000n** [comment]
Thanks for the screenshot.  Should be fixed now.

**Comment by manuelando** [comment]
Perfect thanks :)
