### ISSUE TITLE
Obstacle Course Incorrectly Colliding

### ISSUE THREAD

**Issue by Strayspark7** [buff0000n/dojocad#33]
We have placed an obstacle course under our dojo and on the CAD it says that it will interfere with the open places, but in our dojo it doesn't. 
![image_2022-06-11_150757861](https://user-images.githubusercontent.com/48062226/173191287-56b88e00-6e48-47be-82cb-03fd480c7b0c.png)
![image_2022-06-11_150824957](https://user-images.githubusercontent.com/48062226/173191307-bc7c9d2f-d7b8-4e7d-9762-a8cd421af43a.png)
![image_2022-06-11_150932915](https://user-images.githubusercontent.com/48062226/173191338-6a3328eb-d540-4958-ade6-112f46e25917.png)
![image_2022-06-11_151341634](https://user-images.githubusercontent.com/48062226/173191470-dcd84240-1123-4906-afcd-49da5a36a325.png)

I think the only issue is that the normal obstacle course and not the Architect one is a tad too wide. 

Other than that this tool has been a lifesaver to use!

**Comment by buff0000n** [comment]
Oh, you know what, it's probably because I'm considering the bounding box on the little entry hallway on the open space to be as tall as the whole open space.  I'll check it out.

**Comment by Strayspark7** [comment]
@buff0000n Brilliant, this is a really amazing tool so thanks for being so quick and responsive. 👍
