### ISSUE TITLE
This configuration is working in my Dojo but not in DojoCad (new room Harbingers pass)

### ISSUE THREAD

**Issue by justawarframeuser** [buff0000n/dojocad#36]
Hi!

As i tried to recreate my Dojo in your app i encoutered this bug: Dojocad rejects the emplacement for the new room "Harbinger's pass" but it works fine in the Dojo. I did recreate just the layout that DojoCad rejects but it works for real in the Dojo:

https://buff0000n.github.io/dojocad/index.html?v=2.0,-100,30,0&mz=CbA0CYGZQWgVlABlJA+gVwMYWgRjgsuKsOuLOArpAJxIpA

I join a picture of me in the Dojo in the room as a proof if needed:

![image](https://github.com/buff0000n/dojocad/assets/140863696/e74b359b-41ab-44c4-85a6-4de730edacad)

**Comment by buff0000n** [comment]
Jesus, okay.  I've spent several more hours testing these rooms and they both seem to be slightly bigger on the right side than on the left, **_except_** when put next to the Dry Dock, where there's no difference between right and left sides.  

Uh.  I'm gonna need some time to figure out what's going on or... I dunno... file a bug report with DE.  Bigger one one side than the other is something I can handle, but the Dry Dock thing is breaking my understanding of how room boundaries work.  Right now I'm erring on the side of caution, so your particular configuration is just gonna be red for a while.

**Comment by buff0000n** [comment]
Ugh, okay, this should be fixed now.  I basically had to define a separate boundary for the courtier and harbinger rooms just for checking against the dry dock.  I'm still pretty sure there's a bug here in the game somewhere.

**Comment by buff0000n** [comment]
Ended up slightly adjusting the dry dock's boundary
