### ISSUE TITLE
Courtier's Bliss Dimensions

### ISSUE THREAD

**Issue by BobVonBob** [buff0000n/dojocad#37]
I believe the dimensions of the Courtier's Bliss room are slightly wrong. I'm attempting to build [this layout](https://buff0000n.github.io/dojocad/?v=2.1,-90,34,0&mz=PYJwNAjArGAsAcYAMkD6AbALmAnGAtPCihBgKYEDsi+EEATMmAMwYDGBRnxLGARpFgE6jEhmAEcKBE1boAbmEQQAbE1IATAK7dIalK2AcIOIfnpR9aYAEMC9WI3OXZqTAAsCzJ9-WoQFDIMiMT+FKqQ9CHIYbrBTEioGhpeThZWiWzghCj4vgaxtAyR0YlkAGapYCpCocACOGp5omhsAM5KVWJtALZVqjyJ7gCWkmoQlFakIyyME1OowB3NLMzR9KjuFCv0DgmFXLu1YBszK-iNCWDXYG1JWhC6XAXac2rPaFvCKiSTrl-mPbzVxLexIRD0KRMDag8zg6otJBAA) and the Orokin Lab does not fit. All other labs will fit in that space, but not the Orokin Lab.

The site also says a cross connector, dueling room, barracks, reactor, or small garden should fit there, but they do not.

(DE why did you make the dimensions of the new rooms slightly larger than convenient)

<details>
<summary>Images</summary>

![image](https://github.com/buff0000n/dojocad/assets/34696418/2f56fe5b-a724-4ea1-ab14-ab7fb17ea0af)
![image](https://github.com/buff0000n/dojocad/assets/34696418/e96b5e34-b308-493a-80a3-364b6d442351)
</details>

**Comment by buff0000n** [comment]
Yeah, I still testing the new room, but this one I'm aware of.  You will have to put the Orokin Lab on the other side of the Courtier's Bliss room, and some other smaller room in its place.

**Comment by BobVonBob** [comment]
The Dueling Room also does not fit in that location. The only rooms that fit next to Courtier's Bliss (at least on the right, I saw in another issue that the new rooms are apparently asymmetrical. Wat???) are labs other than the Orokin Lab, the Oracle, elevators, and hallways that do not point towards it.

**Comment by buff0000n** [comment]
Oh, I meant swap the Courtier room and the Dueling room.  And yeah, both of the new rooms are wider on the right than they are on the left because of reasons.

**Comment by buff0000n** [comment]
Okay, all the boundary issues I know about should be fixed now
