### ISSUE TITLE
Old Warframe Clan Layout Not Working In Dojo CAD

### ISSUE THREAD

**Issue by Strayspark7** [buff0000n/dojocad#38]
I've been recently working on an old clan that has some original dojo rooms. What I've found is that in dojoCAD I can't add the right elbow connectors. 

hopefully these images explain better.

![2023-09-08 22_29_16-Warframe DojoCAD](https://github.com/buff0000n/dojocad/assets/48062226/6ed684d4-6302-4af5-a4eb-d6cd067bd110)
![dojo rooms](https://github.com/buff0000n/dojocad/assets/48062226/83f814ab-fedb-4b99-9be4-0761abdbc966)

**Comment by buff0000n** [comment]
With the old dojo rooms I'm limited by what screenshots people send me, and this is the first time I've seen the old elbow connector.

**Comment by Strayspark7** [comment]
yeah, i undertand that i was very surprised to even see the old rooms in this dojo.  but i used two t connectors in place fo the elbow connector and it works.

**Comment by buff0000n** [comment]
Should be fixed now :)
<img width="454" alt="elblow" src="https://github.com/buff0000n/dojocad/assets/43117210/c8222d6b-990e-435f-931a-9483aa5f2a72">

**Comment by Strayspark7** [comment]
Genuinely impressive how quickly you are able to update this tool.  thank you
