### ISSUE TITLE
Wrong overlap for the Obstacle Course and some labs

### ISSUE THREAD

**Issue by Dreamwalk3r** [buff0000n/dojocad#39]
CAD shows an overlap error when trying to place any standard 1x1 room near an obstacle course connected to the tree room, but actually quite a lot of labs fit there (not reactor, though). See attachments:
![Screenshot 2023-10-22 165258](https://github.com/buff0000n/dojocad/assets/1562310/89ccc5b1-94ae-4797-a0ff-c82bf599c17f)
![Warframe 22 10 2023 16_53_51](https://github.com/buff0000n/dojocad/assets/1562310/5e8ddf19-8ebb-477d-9cae-73f7d8fbfd71)

**Comment by buff0000n** [comment]
Jesus.  The bounds on the old obstacle course are so tight that the walls of the chem lab and energy lab literally clip into it.
![chem-lab-clip](https://github.com/buff0000n/dojocad/assets/43117210/9cfb85bc-d11f-405a-9afe-719a8a342195)
![energy-lab-clip](https://github.com/buff0000n/dojocad/assets/43117210/9b7ba139-5155-49d0-98d9-16806ec98733)
There's also a huge plane of fog under the old obstacle course that overlaps heavily under other rooms
![230410_20231022143228_1](https://github.com/buff0000n/dojocad/assets/43117210/406edaa4-7129-4b35-be46-95f94bcc15d9)
and clips into rooms like the open space
![230410_20231022145648_1](https://github.com/buff0000n/dojocad/assets/43117210/902564eb-d326-42fd-a717-a8b81e0207c4)
![230410_20231022151150_1](https://github.com/buff0000n/dojocad/assets/43117210/1fb70387-ea03-4d9e-81f1-8142d481e2fa)
I can adjust the bounds easy enough, both the old obstacle course and the Chem Lab need adjustment.  But I'm also going to have to add some kind of indication of this huge fog plane.

**Comment by buff0000n** [comment]
@Dreamwalk3r Should be fixed now, thanks for the report!

**Comment by Dreamwalk3r** [comment]
@buff0000n thank you for the awesome tool :)
