### ISSUE TITLE
Incorrect boundary for Harbinger's Pass and Courtier's Bliss

### ISSUE THREAD

**Issue by MacDB** [buff0000n/dojocad#42]
Images:
![image](https://github.com/buff0000n/dojocad/assets/58088837/4dbcd079-bcda-4410-9f00-74f55da15452)
![image](https://github.com/buff0000n/dojocad/assets/58088837/48e44190-35ae-4801-a3ea-4701ae9d855d)

Both settings are possible to build in game. It seems that both rooms are half a square too wide.

**Comment by buff0000n** [comment]
@MacDB 
Those rooms actually *are* slightly wider on one side.  This works:
<img width="169" alt="Screen Shot 2023-12-19 at 8 27 59 PM" src="https://github.com/buff0000n/dojocad/assets/43117210/dfa0543b-e355-4152-ac64-bd7f5e24ef08">

But this does not:
<img width="168" alt="Screen Shot 2023-12-19 at 8 28 02 PM" src="https://github.com/buff0000n/dojocad/assets/43117210/21985bec-3e0e-42da-b0ea-7c38eefff181">

I did a massive amount of testing on this back in the summer, and I just verified in-game once more time to check.

You'll find that if you actually build your second picture, then you can't build much of anything from the southeast door in that hall.  Only rooms that can be placed without having a door on their left side.  However, with the first picture and the smaller Duviri room, you can actually place a lot of the 6-door halls off the bottom of that one. 

What this actually shows is that many of the 6-door halls have slightly narrower boundaries away from the doors.... which sucks.

I have to tweak the boundaries on pretty much every 6 and 10 door hall by half a meter, all except for the Inspiration Hall, which can't be built there in either of your pictures.  

Anyway, I've fixed the bounds on those rooms in the DojoCAD code, so they won't turn red in your scenario anymore.  However, fixing the graphics to show that tiny bump in the boundary will happen... maybe never.  I did a similar tweak on the Dry Dock back in the summer during my initial testing with these damn Duviri rooms, and that was as huge pain in the ass.

**Comment by MacDB** [comment]
Thanks, much appreciated!
