### ISSUE TITLE
Problems with dry dock actual "box"

### ISSUE THREAD

**Issue by Lucanique** [buff0000n/dojocad#5]
I planned my dojo to have some reactors next to the dry docks, on another floor, however, on the website it was considered valid, but on warframe it said it had no space.

So yeah, dry docks are hecking huge haha

my dojo schematics for reference 

![dojo](https://user-images.githubusercontent.com/51333733/86318552-a576ad80-bc08-11ea-84ed-720fb9f04e2e.png)

**Comment by Lucanique** [comment]
https://buff0000n.github.io/dojocad/index.html?v=2,1,-222,-1&mz=BYRgNADJ0Q+gxgU2gWgCxrC8d71SAGxY6wBOyKAzAExhElhXnK0nHb0L5QOdwB7MlirhsHcMwA2ArGjpoAHI2Z5oSxnApM6fcCFjAAltEKYocKQBcwacBt6wplNMQdMn+dMsUWPUgCNbYl9oAwATcOgaGnMwGhYROlDOVS8QAHZiGLi4cIBXEiz6AE46C1gBAEMsGkVlKiplKASBLzrlEtzYK2Ba+vjYmAQADxIMQbiDeDGUGghlHOhVWdiWoahVYWximgBWYhaEIKgU8AT4GzYNTgNtNjP47jAzW2V+IA

**Comment by buff0000n** [comment]
...huh.  I just built a path to that spot in my dojo and I can place a reactor there.

Are you sure your elevator goes down and not up?  You can build a reactor on the floor below an Inspiration Hall, but you can't build a reactor on the floor above one.
