### ISSUE TITLE
Problems with clan hall collision

### ISSUE THREAD

**Issue by wingcobob** [buff0000n/dojocad#7]
This is my clan dojo as it is in game right now:
https://buff0000n.github.io/dojocad/?v=2,-147,47,0&mz=BYRgNAtAzJAsBsYAMyD6BjdkYCZls20gE5Z8lUAnAUyIhB0RQprB2JLJRCtugFZO+KKmB4I-cHm6iYsQdLA90AFxIdFLPsQ7RmaVhB1goXNhj4wo+nBizQ2StMDISpTnsEH0QCj6gATAMgcAHY-cBEAewAjEPCQpERwChVgMHlHFIxKDMF+bnMAgFc8uGS0KNyIeFC4QWyAGyjIWrB4QttGuPoocAhYMib7YwGKikbtDlgADicutV7wWBgpCzpGJwpCBzxpVCisEGPHPB4Ac0bISVOCAGciTf3VIgLT1HOHtzA36SA
As you can see, the clan hall is colliding with the great & greater halls on the bottom level. It works fine in game though ¯\\(ツ)/¯. Apart from that the tool has been great so far 👍 
![dojo bottom floor](https://user-images.githubusercontent.com/71791191/94074591-834c9000-fdf1-11ea-9a34-98afd06548fd.png)

**Comment by buff0000n** [comment]
@wingcobob Huh, that's interesting.  I know for a fact that something like [this](https://buff0000n.github.io/dojocad/index.html?v=3,-12,0,0&mz=BYRgNADJ0Q+gxvaBaALADhgpBmATGGplHImAGyqEZbAGUySwBOApmPoSOdHkA) doesn't work for either of the Clan Hall or Clan Greater Hall.  But there's no denying that screenshot.

My only explanation is that there's some kind of notch in each corner of the Clan Hall bounding box.  Unfortunately it's pretty hard to test conclusively for that in any way other than what you've done here, even if I did hav any room around my starter hall.  Maybe something like [this](https://buff0000n.github.io/dojocad/index.html?v=4,-86,123,0&mz=BYRgNADJ0Q+gxvaBaALADhgpVnqgdmAMwBMYeBksARuGRagGzSlA), but I ain't tearing half my dojo up just for that.

**Comment by buff0000n** [comment]
Should be fixed now.  Thanks for the heads up!
